PREFIX dbr: <http://dbpedia.org/resource/>
PREFIX dbo: <http://dbpedia.org/ontology/>

# The endpoint must support AS
SELECT ?album (datatype(?album) AS ?albumDataType)
WHERE {
  ?album dbp:artist dbr:The_Offspring
} LIMIT 10
