PREFIX dbr: <http://dbpedia.org/resource/>
PREFIX dbo: <http://dbpedia.org/ontology/>

SELECT ?bandMember ?genre
WHERE {
  dbr:The_Offspring dbo:formerBandMember ?bandMember .
  ?bandMember dbo:genre ?genre .
  # removes ?bandMember
  MINUS { ?bandMember dbo:genre dbr:Skate_punk }
}
