PREFIX dbr: <http://dbpedia.org/resource/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbp: <http://dbpedia.org/property/>

SELECT ?album ?released datatype(?released)
WHERE {
  ?album dbo:artist dbr:The_Offspring .
  ?album dbp:released ?released . 
  FILTER (datatype(?released) = <http://www.w3.org/2001/XMLSchema#date>) .
  # OFFSET 3 skips the first 3 entries
} ORDER BY ASC(?released) OFFSET 3 LIMIT 10
