PREFIX dbr: <http://dbpedia.org/resource/>
PREFIX dbo: <http://dbpedia.org/ontology/>

# Combines results from different patterns.
# If an item matches any of the patterns, it's included in the output along with all the information associated with it.
SELECT ?formerBandMember ?genre
WHERE {
  dbr:The_Offspring dbo:formerBandMember ?formerBandMember ;
                    dbo:genre ?genre .
  # The format for UNION requires each pattern to be enclosed in braces {...}.
  # Hence there are braces around each pattern.
  { ?formerBandMember dbo:genre dbr:Skate_punk }
  UNION
  { ?formerBandMember dbo:genre dbr:Metalcore  }
}
