PREFIX dbr: <http://dbpedia.org/resource/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbp: <http://dbpedia.org/property/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?title ?album
WHERE {
  # sequence path
  dbr:Original_Prankster dbo:previousWork/dbo:previousWork/dbo:previousWork ?title .
  OPTIONAL { ?title dbp:album ?album }
}
